/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as PricingServiceIndexRouteImport } from './routes/pricing/$service/index'
import { Route as PricingServiceTierRouteImport } from './routes/pricing/$service/$tier'

const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingServiceIndexRoute = PricingServiceIndexRouteImport.update({
  id: '/pricing/$service/',
  path: '/pricing/$service/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingServiceTierRoute = PricingServiceTierRouteImport.update({
  id: '/pricing/$service/$tier',
  path: '/pricing/$service/$tier',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/pricing/': typeof PricingIndexRoute
  '/pricing/$service/$tier': typeof PricingServiceTierRoute
  '/pricing/$service/': typeof PricingServiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/pricing': typeof PricingIndexRoute
  '/pricing/$service/$tier': typeof PricingServiceTierRoute
  '/pricing/$service': typeof PricingServiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/pricing/': typeof PricingIndexRoute
  '/pricing/$service/$tier': typeof PricingServiceTierRoute
  '/pricing/$service/': typeof PricingServiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/process'
    | '/pricing/'
    | '/pricing/$service/$tier'
    | '/pricing/$service/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/process'
    | '/pricing'
    | '/pricing/$service/$tier'
    | '/pricing/$service'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/process'
    | '/pricing/'
    | '/pricing/$service/$tier'
    | '/pricing/$service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ProcessRoute: typeof ProcessRoute
  PricingIndexRoute: typeof PricingIndexRoute
  PricingServiceTierRoute: typeof PricingServiceTierRoute
  PricingServiceIndexRoute: typeof PricingServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/$service/': {
      id: '/pricing/$service/'
      path: '/pricing/$service'
      fullPath: '/pricing/$service/'
      preLoaderRoute: typeof PricingServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/$service/$tier': {
      id: '/pricing/$service/$tier'
      path: '/pricing/$service/$tier'
      fullPath: '/pricing/$service/$tier'
      preLoaderRoute: typeof PricingServiceTierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ProcessRoute: ProcessRoute,
  PricingIndexRoute: PricingIndexRoute,
  PricingServiceTierRoute: PricingServiceTierRoute,
  PricingServiceIndexRoute: PricingServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
